config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :locations
  resources :beauty_places
  resources :employees

  resources :deals, only: [:index, :show]
  get '/owners/edit_deal/:id', to: 'deals#edit'

  resources :beauty_places, has_many: :employees, shallow: true
  resources :beauty_places do
    resources :deals
  end

  get '/search/deals', to: 'search#deals'
  get '/sort_by_discount', to: 'search#discount_descending', as: 'discount_descending'
  get '/owners_deals/:id/edit', to: 'owners#deals_edit', as: 'owner_deals_edit'
  post '/beauty_places/save', to: 'beauty_places#save'

  devise_for :users, :skip => [:sessions],
                     :controllers => {
                       :omniauth_callbacks => "users/omniauth_callbacks",
                       :registrations => "users/registrations",
                       :confirmations => "users/confirmations"
                     }
  as :user do
    get 'sign-in' => 'users/sessions#new', :as => :new_user_session
    post 'sign-in' => 'users/sessions#create', :as => :user_session
    delete 'sign-out' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  # must be below devise_for
  resources :users, only: [:index, :show, :destroy, :update, :delete]
end

app/views/partials/_footer.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">BeautyPin, llc</span>
  </div>
</footer>

app/views/partials/_form_errors.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/partials/_nav.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <nav class="navbar navbar-light bg-faded" role="navigation" style="background-color: #">
      <%= link_to 'BeautyPin', root_path, class: 'navbar-brand' %>
      <% if user_signed_in? %>
        <%= render 'partials/signed_in_nav' %>
      <% else %>
        <%= render 'partials/signed_out_nav' %>
      <% end %>
    </nav>
  </div>
</header>

app/views/partials/_search.erb
<div class="search-bar">
  <form class='search-form form-inline'>
    <ul class='list-inline'>
      <li class='list-inline-item'>Current Location:</li>
      <li class='list-inline-item'><%= text_field_tag :location, params[:location], class: 'form-control', value: (current_user.city + ' ' + current_user.state) %></li>
      <li class='list-inline-item'><%= text_field_tag :search, params[:search], class: 'form-control', id: "lastSearch", value: @last_search || ''  %></li>
      <li class='list-inline-item'>
        <button type="button" class="search-submit btn btn-primary-outline search">Search</button>
      </li>
    </ul>
  </form>
</div>

app/views/partials/_search_bar.erb
<% if user_signed_in? %>
  <%= render 'partials/search' %>
<% end %>

app/views/partials/_signed_in_nav.erb
<div class="nav signed-in-nav">
    <%= link_to "Deals", deals_path, class: 'nav-item btn btn-secondary-outline', data: {'nav-deals': '#'}, remote: true %>
    <!-- <%= link_to "BeautyPlaces", beauty_places_path, class: 'nav-item btn btn-secondary-outline' %> -->
    <% if current_user.admin? %>
      <%= link_to "Users", users_path, class: 'nav-item btn btn-secondary-outline' %>
    <% end %>
    <%= link_to "Log out", destroy_user_session_path, class: 'nav-item  btn btn-secondary-outline' , method: "delete" %>
</div>

app/views/partials/_signed_out_nav.erb
<div class="nav signed-out-nav">
  <%= link_to 'Sign In', new_user_session_path, class: "btn btn-primary", role: "button" %>

  <%= link_to 'Register', new_user_registration_path, class: "btn btn-primary", role: "button" %>

</div>