config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :locations
  resources :beauty_places
  resources :employees

  resources :deals, only: [:index, :show]
  get '/owners/edit_deal/:id', to: 'deals#edit'

  resources :beauty_places, has_many: :employees, shallow: true
  resources :beauty_places do
    resources :deals
  end

  get '/search/deals', to: 'search#deals'
  get '/sort_by_discount', to: 'search#discount_descending', as: 'discount_descending'
  get '/owners_deals/:id/edit', to: 'owners#deals_edit', as: 'owner_deals_edit'
  post '/beauty_places/save', to: 'beauty_places#save'

  devise_for :users, :skip => [:sessions],
                     :controllers => {
                       :omniauth_callbacks => "users/omniauth_callbacks",
                       :registrations => "users/registrations",
                       :confirmations => "users/confirmations"
                     }
  as :user do
    get 'sign-in' => 'users/sessions#new', :as => :new_user_session
    post 'sign-in' => 'users/sessions#create', :as => :user_session
    delete 'sign-out' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  # must be below devise_for
  resources :users, only: [:index, :show, :destroy, :update, :delete]
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  has_many :services
  accepts_nested_attributes_for :services

  belongs_to :beauty_place

  has_one :locatable
  has_one :location, through: :locatable

  validates :title, presence: true, length: { minimum: 4 }
  validates :discount, presence: true
  validates :description, presence: true

  def self.policy_class
    DealPolicy
  end

  def self.search(search)
    if search
      where("title like ?", "%#{search}%")
    else
      Deal.all
    end
  end

  def user_id
    beauty_place.user.id
  end

  # def update_attributes(title: nil, description: nil, disount: nil)
  #   self.title = title
  #   self.description = description
  #   self.discount = discount
  # end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def index
    @deals = Deal.search(params[:search]).page params[:page]
    @deals = policy_scope(@deals)

    respond_to do |format|
      format.html
      format.json { render json: @deals }
    end
  end

  def edit
    @deal = Deal.find(params[:id])
    @beauty_place = @deal.beauty_place
    authorize @deal
    respond_to do |format|
      format.html
      format.json { render json: { deal: @deal } }
    end
  end


  def new
    @beauty_place = BeautyPlace.find params[:beauty_place_id]
    @deal = @beauty_place.deals.build
    authorize @beauty_place
    respond_to do |format|
      format.html
      format.json { render json: { deal: @deal } }
    end
  end

  def create
    @beauty_place = BeautyPlace.find(params[:beauty_place_id])
    @deal = @beauty_place.deals.create deal_params @beauty_place
    authorize @deal
    respond_to do |format|
      if @beauty_place.valid?
        url = beauty_place_deal_path id: @deal.id
        format.html { redirect_to url, notice: 'Deal was successfully created.' }
        format.js
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @beauty_place = BeautyPlace.find_by(params[:beauty_place_id])
    @deal = @beauty_place.deals.find params[:id]
    authorize @deal
    respond_to do |format|
      if @deal.update_attributes(deal_params(@beauty_place))
        format.html { render :show, :layout => false }
        format.json { render :json => @deal }
      else
        format.html { render :edit, :layout => false }
      end
    end
  end

  def show
    @deal = Deal.find_by id: params[:id]
    authorize @deal
    respond_to do |format|
      format.html { render layout: false }
      format.js
      format.json { render json: @deal.to_json(include: [:beauty_place]) }
    end
  end

  def destroy
    @deal = Deal.find_by id: params[:id]
    authorize @deal
    @deal.delete
    # respond_to do |format|
    #   format.html { render :index, layout: false }
    # end
    redirect_to :back
  end

  private
  def deal_params(beauty_place)
    params.require(:deal).permit(policy(Deal).permitted_attributes(beauty_place))
  end

  def search_params
    params.require(:search).permit(policy(Deal).permitted_attributes)
  end
end

app/views/deals/_deal.erb
</ul>
  <li>Place of Beauty: <%= deal.beauty_place.name %></li>
  <li>title: <%= deal.title %></li>
  <li>description: <%= deal.description %></li>
  <li>discount: <%= deal.discount %></li>
<ul>

app/views/deals/_form.erb
<%= form_for [@beauty_place, @deal], remote: true do |deal_form| %>
  <% if @deal.errors.any? %>
    <%= render 'partials/form_errors', target: @deal %>
  <% end %>

  <div class="form-group">
    <%= deal_form.label :title %>
    <%= deal_form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= deal_form.label :description %>
    <%= deal_form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= deal_form.label :discount %>
    <%= deal_form.text_field :discount, class: 'form-control', placeholder: '10%, 15%, etc.' %>
  </div>
  <%= deal_form.submit 'Submit' %>
<% end %>

app/views/deals/edit.erb
<h2>Edit Deal that belongs to <%= @deal.beauty_place.name %></h2>
<%= render 'deals/form' %>

app/views/deals/index.erb
<h2>All deals</h2>
<table id="dealsTable" class="table">
  <tr>
    <th>place</th>
    <th>title</th>
    <th><%= link_to 'discount', discount_descending_path, id: 'discount', 'sort-by-discount': '#' %></th>
    <th>description</th>
  </tr>
  <tbody id='dealsTableBody'>

  <% @deals.each do |deal| %>
    <tr>
      <td><%= link_to deal.beauty_place.name, beauty_place_deal_path(deal, deal.beauty_place), remote: true %></td>
      <td><%= link_to deal.title, '#', 'data-deal-show': deal_path(deal), remote: true  %></td>
      <td><%= link_to deal.discount %></td>
      <td><%= deal.description %></td>
    </tr>
  <% end %>

  </tbody>
</table>
<%= paginate @deals %>

<% if current_user.owner? && !@beauty_place.nil? %>
  <%= link_to 'New Deal', new_beauty_place_deal_path(@beauty_place, @deal), method: :get, class: 'btn btn-primary' %>
<% end %>

app/views/deals/new.erb
<h2>Create New Deal for <%= @beauty_place.name.capitalize %></h2>
<%= render 'form' %>

app/views/deals/show.erb
<%= render 'deal', deal: @deal %>